services:
  finance-app:
    build:
      context: .
      target: development
    ports:
      - 8080:8080
    develop:
      watch:
        - action: rebuild
          path: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=finance_db;Username=dev_user;Password=password
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: finance-db
    restart: always
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dev_user", "-d", "finance_db"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  postgres-data: