name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Check Formatting
        run: dotnet format --verify-no-changes || echo "Code formatting issues detected."
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test with Coverage
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
