name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker Image
        run: |
          docker build --target build -t financeapp:latest .
            
      - name: Run Tests in Docker Container
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -e DOCKER_HOST=unix:///var/run/docker.sock \
            financeapp:latest dotnet test --configuration Release --no-build --verbosity normal

      - name: Save Docker Image as Artifact
        run: |
          docker save -o /tmp/financeapp.tar financeapp:latest

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: financeapp-image-artifact
          path: /tmp/financeapp.tar

  build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download Cached Docker Image
        uses: actions/download-artifact@v4
        with:
          name: financeapp-image-artifact
          path: /tmp

      - name: Load Docker Image
        run: |
          docker load -i /tmp/financeapp.tar

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag financeapp:latest ${{ secrets.DOCKER_USERNAME }}/financeapp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/financeapp:latest